-- =============================================
-- SGBD : PostgreSQL
-- =============================================

-- (Re)création propre : on supprime en respectant les FKs
DROP TABLE IF EXISTS visite CASCADE;
DROP TABLE IF EXISTS evaluation CASCADE;
DROP TABLE IF EXISTS apprenti CASCADE;
DROP TABLE IF EXISTS maitre_apprentissage CASCADE;
DROP TABLE IF EXISTS entreprise CASCADE;
DROP TABLE IF EXISTS utilisateur CASCADE;
DROP TABLE IF EXISTS annee_academique CASCADE;

-- Fonction/trigger pour mettre à jour date_modification
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.date_modification := NOW();
RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- =============================================
-- Table : annee_academique
-- =============================================
CREATE TABLE annee_academique (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  annee VARCHAR(20) NOT NULL UNIQUE,
                                  active BOOLEAN NOT NULL DEFAULT FALSE,
                                  date_creation TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                                  date_activation TIMESTAMPTZ NULL
);

CREATE INDEX idx_annee_active ON annee_academique(active);

-- =============================================
-- Table : utilisateur (tuteur-enseignant)
-- =============================================
CREATE TABLE utilisateur (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             username VARCHAR(100) NOT NULL UNIQUE,
                             password VARCHAR(255) NOT NULL,
                             prenom VARCHAR(100) NOT NULL,
                             nom VARCHAR(100) NOT NULL,
                             email VARCHAR(150) NOT NULL,
                             role VARCHAR(50) NOT NULL DEFAULT 'ROLE_TUTEUR',
                             enabled BOOLEAN NOT NULL DEFAULT TRUE,
                             date_creation TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                             date_derniere_connexion TIMESTAMPTZ NULL
);

-- =============================================
-- Table : entreprise
-- =============================================
CREATE TABLE entreprise (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            raison_sociale VARCHAR(200) NOT NULL,
                            adresse TEXT,
                            informations_acces TEXT
);

-- =============================================
-- Table : maitre_apprentissage
-- =============================================
CREATE TABLE maitre_apprentissage (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      nom VARCHAR(100) NOT NULL,
                                      prenom VARCHAR(100) NOT NULL,
                                      poste VARCHAR(150),
                                      email VARCHAR(150),
                                      telephone VARCHAR(20),
                                      remarques TEXT,
                                      entreprise_id BIGINT NOT NULL REFERENCES entreprise(id) ON DELETE CASCADE
);

-- =============================================
-- Table : apprenti
-- =============================================
CREATE TABLE apprenti (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          nom VARCHAR(100) NOT NULL,
                          prenom VARCHAR(100) NOT NULL,
                          email VARCHAR(150) NOT NULL,
                          telephone VARCHAR(20),
                          programme VARCHAR(100),
                          annee_academique VARCHAR(20) NOT NULL,
                          majeure VARCHAR(150),
                          niveau VARCHAR(10) NOT NULL DEFAULT 'I1',
                          archive BOOLEAN NOT NULL DEFAULT FALSE,

    -- Informations entreprise
                          entreprise_id BIGINT NOT NULL REFERENCES entreprise(id) ON DELETE RESTRICT,
                          maitre_apprentissage_id BIGINT NOT NULL REFERENCES maitre_apprentissage(id) ON DELETE RESTRICT,

    -- Mission
                          mission_mots_cles TEXT,
                          mission_metier_cible VARCHAR(200),
                          mission_commentaires TEXT,

    -- Tuteur enseignant
                          tuteur_enseignant_id BIGINT NOT NULL REFERENCES utilisateur(id) ON DELETE RESTRICT,
                          feedback_tuteur TEXT,

                          remarques_generales TEXT,
                          date_creation TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                          date_modification TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_apprenti_nom ON apprenti(nom);
CREATE INDEX idx_apprenti_annee ON apprenti(annee_academique);
CREATE INDEX idx_apprenti_archive ON apprenti(archive);
CREATE INDEX idx_apprenti_niveau ON apprenti(niveau);

-- Trigger pour maintenir date_modification à NOW() sur UPDATE
DROP TRIGGER IF EXISTS tr_apprenti_set_updated_at ON apprenti;
CREATE TRIGGER tr_apprenti_set_updated_at
    BEFORE UPDATE ON apprenti
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =============================================
-- Table : visite
-- =============================================
CREATE TABLE visite (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        apprenti_id BIGINT NOT NULL REFERENCES apprenti(id) ON DELETE CASCADE,
                        date_visite DATE,
                        format VARCHAR(20),
                        commentaires TEXT,
                        date_creation TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================
-- Table : evaluation
-- =============================================
CREATE TABLE evaluation (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            apprenti_id BIGINT NOT NULL REFERENCES apprenti(id) ON DELETE CASCADE,

    -- Évaluation mémoire/rapport
                            memoire_theme VARCHAR(255),
                            memoire_note NUMERIC(4,2),
                            memoire_commentaires TEXT,

    -- Évaluation soutenance
                            soutenance_date DATE,
                            soutenance_note NUMERIC(4,2),
                            soutenance_commentaires TEXT,

                            remarques_generales TEXT,
                            date_creation TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                            date_modification TIMESTAMPTZ NOT NULL DEFAULT NOW(),

                            CONSTRAINT unique_evaluation_apprenti UNIQUE (apprenti_id)
);

-- Trigger pour date_modification
DROP TRIGGER IF EXISTS tr_evaluation_set_updated_at ON evaluation;
CREATE TRIGGER tr_evaluation_set_updated_at
    BEFORE UPDATE ON evaluation
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- (Facultatif) Ajoute des commentaires lisibles après coup :
-- COMMENT ON TABLE annee_academique IS 'Format: 2025-2026; une seule active';
-- etc.
